INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_HUMMINGBIRD_XMLRPC hummingbird_xmlrpc)

FIND_PATH(
    HUMMINGBIRD_XMLRPC_INCLUDE_DIRS
    NAMES hummingbird_xmlrpc/api.h
    HINTS $ENV{HUMMINGBIRD_XMLRPC_DIR}/include
        ${PC_HUMMINGBIRD_XMLRPC_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    HUMMINGBIRD_XMLRPC_LIBRARIES
    NAMES gnuradio-hummingbird_xmlrpc
    HINTS $ENV{HUMMINGBIRD_XMLRPC_DIR}/lib
        ${PC_HUMMINGBIRD_XMLRPC_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HUMMINGBIRD_XMLRPC DEFAULT_MSG HUMMINGBIRD_XMLRPC_LIBRARIES HUMMINGBIRD_XMLRPC_INCLUDE_DIRS)
MARK_AS_ADVANCED(HUMMINGBIRD_XMLRPC_LIBRARIES HUMMINGBIRD_XMLRPC_INCLUDE_DIRS)

